path:
  image_net: /local/reyhasjb/datasets/Imagenet #100 class or 1000 class
  image_net_train: /home/mohsen/Desktop/Academia/MasterRUB/ResearchProjects/INI/masking_comparison/image/data/mini_imagenet_train
  image_net_val: /home/mohsen/Desktop/Academia/MasterRUB/ResearchProjects/INI/masking_comparison/image/data/mini_imagenet_val
  image_net_test: /home/mohsen/Desktop/Academia/MasterRUB/ResearchProjects/INI/masking_comparison/image/data/mini_imagenet_test 
  recnstructed_imge: /home/abghamtm/work/masking_comparison/image/reconstruction/ #100 or 1000 classes
  vqvae_model: /home/abghamtm/work/masking_comparison/model_checkpoints/vqvae/
  classifier_model:
  distilbert_model: 

params:
  vqvae:
    batch_size: 128
    latent_loss_weight: 0.25
    diversity_loss_weight: 0.001
    num_epochs: 100
    lr: 1e-4
    weight_decay: 1e-4

credentials:
  neptune_api_token: eyJhcGlfYWRkcmVzcyI6Imh0dHBzOi8vYXBwLm5lcHR1bmUuYWkiLCJhcGlfdXJsIjoiaHR0cHM6Ly9hcHAubmVwdHVuZS5haSIsImFwaV9rZXkiOiIwODg4OTU0Yy0xODAyLTRiM2QtYjYzYi0xMWQxYThmYWJlOWQifQ==

multiprocessing:
  gpu:
    gpu_ids: 
    threshold: 5.0
    filter_by_threshold: true
