path:
  image_net: /local/reyhasjb/datasets/Imagenet1k #1000 classes of imagenet - contains both train and validation sets
  image_net_train: /local/reyhasjb/datasets/Imagenet1k/train
  image_net_train_local: /home/abghamtm/work/datasets/Imagenet1k/train
  image_net_val: /local/reyhasjb/datasets/Imagenet1k/val
  image_net_val_local: /home/abghamtm/work/datasets/Imagenet1k/val
  image_net_test: 
  recnstructed_storage: 
    image:
      train: /home/abghamtm/work/mask_image_reconstruct_image/reconstruction/image/reconstructed/train
      val: /home/abghamtm/work/mask_image_reconstruct_image/reconstruction/image/reconstructed/val
    latent_space: /home/abghamtm/work/mask_image_reconstruct_image/reconstruction/latent_space
  model: 
    vqvae: /home/abghamtm/work/mask_image_reconstruct_image/models_checkpoint/vqvae
    classifier: 
      resnet:
        dir: /home/abghamtm/work/mask_image_reconstruct_image/models_checkpoint/resnet

    distilbert: /home/abghamtm/work/mask_image_reconstruct_image/models_checkpoint/distilbert

params:
  vqvae:
    batch_size: 128
    latent_loss_weight: 0.25
    diversity_loss_weight: 0.001
    num_epochs: 100
    lr: 1e-4
    weight_decay: 1e-4
    best_model_epoch: 28

credentials:
  neptune_api_token: ??

multiprocessing:
  gpu:
    gpu_ids: 
    threshold: 5.0
    filter_by_threshold: True
