path:
  image_net: /local/reyhasjb/datasets/Imagenet1k #1000 classes of imagenet - contains both train and validation sets
  image_net_train: /local/reyhasjb/datasets/Imagenet1k/train
  image_net_val: /local/reyhasjb/datasets/Imagenet1k/val
  image_net_test: 
  recnstructed_image: 
    train: /home/abghamtm/work/mask_image_reconstruct_image/image/reconstructed/train
    val: /home/abghamtm/work/mask_image_reconstruct_image/image/reconstructed/val
  vqvae_model: /home/abghamtm/work/mask_image_reconstruct_image/models_checkpoint/vqvae
  classifier_model: /home/abghamtm/work/mask_image_reconstruct_image/models_checkpoint/resnet
  distilbert_model: /home/abghamtm/work/mask_image_reconstruct_image/models_checkpoint/distilbert

params:
  vqvae:
    batch_size: 128
    latent_loss_weight: 0.25
    diversity_loss_weight: 0.001
    num_epochs: 100
    lr: 1e-4
    weight_decay: 1e-4

credentials:
  neptune_api_token: eyJhcGlfYWRkcmVzcyI6Imh0dHBzOi8vYXBwLm5lcHR1bmUuYWkiLCJhcGlfdXJsIjoiaHR0cHM6Ly9hcHAubmVwdHVuZS5haSIsImFwaV9rZXkiOiIwODg4OTU0Yy0xODAyLTRiM2QtYjYzYi0xMWQxYThmYWJlOWQifQ==

multiprocessing:
  gpu:
    gpu_ids: 
    threshold: 5.0
    filter_by_threshold: True
